---
- name: Create a login user
  user:
    name: ansible
    password: '<changeme>' # use mkpasswd --method=sha-512 to generate a hashed password
    groups: # Empty by default, here we give it some groups
      - docker
      - sudo
    uid: 1001
    state: present
    shell: /bin/bash       # Defaults to /bin/bash
    system: no             # Defaults to no
    createhome: yes        # Defaults to yes
    home: /home/ansible  # Defaults to /home/<username>