version: "3.3"

services:
  homer:
    image: b4bz/homer
    restart: always
    container_name: homer
    volumes:
      - /opt/homer/assets/:/www/assets
    user: "1001"
    environment:
      - INIT_ASSETS=1
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homer.rule=Host(`homer.{{ hostname }}`)"
      - "traefik.http.routers.homer.entrypoints=websecure"
      - "traefik.http.services.homer.loadbalancer.server.port=8080"
      - "traefik.http.routers.homer.service=homer"
      - "traefik.http.routers.homer.tls.certresolver=myresolver"

networks:
  traefik:
    external: true