---
- name: Print a message
  ansible.builtin.debug:
    msg: 'Logging in as {{ hostname }}'

- name: Create traefik network
  docker_network:
    name: traefik


- name: Ensure /opt/traefik exists
  file: 
    path: /opt/traefik
    state: directory 
    owner: ansible
    group: docker

- name: Template docker-compose
  template:
    src: docker-compose.yml
    dest: /opt/traefik/docker-compose.yml

- name: Tear down existing services
  docker_compose:
    project_src: /opt/traefik
    state: absent
    remove_orphans: yes

- name: Create and start services
  docker_compose:
    project_src: /opt/traefik
